# Limit of entities in a chunk
# -1 disables
chunk: -1
# Amount of entities that can exist in a certain world at the same time
# -1 disables
global: -1
# Purge all monsters/ambient mobs in a chunk on load (ignores named ones)
purge: false
# You can add more reasons here
reasons:
  # The spawn reason
  breeding:
    # Limit if total entity count (not only the spawned mob) in chunk is above this value
    chunklimit: 50
  natural:
    # The type of the entity that is spawning
    pillager:
      # How many of that entity can be in the radius
      count: 4
      # The radius to check for
      radius: 16
  nether_portal:
    pig_zombie:
      count: 50
      radius: 64
      # Whether or not to disable the AI
      dumb: false
  # Spawn reasons don't need an entity type:
  spawner:
    count: 20
    radius: 50
  village_defense:
    count: 1
    radius: 16
  place:
    boat:
      count: 10
      radius: 6
    armor_stand:
      count: 10
      radius: 2